travis:
  secure:
    BINSTAR_TOKEN: F67pkU7WUPky/06z6LgwwbxoH9Fg4l4Qzv0or3GZQn7+Z0q1Zob2mFaSLPJf5U2pxLfbPeIUd9l1VQUt/8ozbjbEUfgNnMMDrYCw9fwAZJva5AkBam+6RynbaaOzEUzKgVFQDN5aQLjNWNYZox6WvwmhJrashxh1JXtf8x9My215K9Btg4A6iUIjAjF0Txn8IaGXEfcoAmQUWrpPJ8kpN5nXE6O46SJpplUdOG2OdWj25MofwyJnOSYJppsPUY7wqWxKfoPinocvbse8PmBrY3Qo5oWPNBSV07FdlL08RgAGXGykdLbW5sH5rbwp2YKViUY3IYl/SPptcwBE0DuTF0PVYH+mgLFj8q7IdY5wpMFo4BaKlY3H+idv69ujkJniLQu85hMvvoU74/JxS25N3Co34ThgQS0o5jTMCa6jZT8SgVlxQlYM92wU9kEm2+RumnhHqGycbPcmiUvjUftoek+dn8AKgFDbYVCh7gleC9jH7tWVjNjYz9t5vZKqJ40dyaCwDiI7uwMi+KEO14G2jOW5wCxcvni75LHgAuPLH6VDFxyxLzWN2il/E/AEk9imBYIzzMlWq38cFE0e6oXkfCRefKWZ56WtrpKSI6qcMGAKRe2dFilQowhzqjhyzSgv4OW45ihGVJ1qvu9KGkUMpqFinupSX0VWNzeZ5viRHx0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
